name: "CodeCheck"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn clean package install
        
      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: mcMMO.jar
          path: target/mcMMO*.jar
